openapi: 3.0.0
info:
  title: NHS Common API
  description: NHS Common API
  version: "0.0.1"
#servers:
 # - url: http://api.example.com/v1
 #   description: Optional server description, e.g. Main #(production) server
 # - url: http://staging-api.example.com
 #   description: Optional server description, e.g. Internal staging server for testing
components:
#-------------------------------
# Reusable operation parameters
#-------------------------------
 parameters:
    Ssp-TraceIDParam:      # Can be referenced via '#/components/parameters/Ssp-TraceIDParam'
      name: Ssp-TraceID
      in: header
      description: Consumer trace identifier
      required: true
      x-example: 09a01679-2564-0fb4-5129-aecc81ea2706
      schema:
        type: string
    Ssp-FromParam:      # Can be referenced via '#/components/parameters/Ssp-FromParam'
      name: Ssp-From
      in: header
      description: Consumer ASID
      required: true
      x-example: 200000000359
      schema:
        type: string
    Ssp-ToParam:      # Can be referenced via '#/components/parameters/Ssp-ToParam'
      name: Ssp-To
      in: header
      description: Provider ASID
      required: true
      x-example: 918999198993
      schema:
        type: string        
    Ssp-InteractionID:      # Can be referenced via '#/components/parameters/Ssp-InteractionID'
      name: Ssp-InteractionID
      in: header
      description: Provider ASID
      required: true
      schema:
        type: string 
        default: urn:nhs:names:services:gpconnect:fhir:rest:read:metadata-1
    Authorization:      # Can be referenced via '#/components/parameters/SAuthorization'
      name: Authorization
      in: header
      description: Authorization header containing JWT
      required: true
      x-example: |-
            {
              "iss": "https://orange.testlab.nhs.uk/",
              "sub": "1",
              "aud": "https://orange.testlab.nhs.uk/gpconnect-demonstrator/v1/fhir",
              "exp": <<expiry>>,
              "iat": <<issued_at>>,
              "reason_for_request": "directcare",
              "requested_scope": "organization/*.read",
              "requesting_device": {
                "resourceType": "Device",
                "identifier": [
                  {
                    "system": "https://orange.testlab.nhs.uk/gpconnect-demonstrator/Id/local-system-instance-id",
                    "value": "gpcdemonstrator-1-orange"
                  }
                ],
                "model": "GP Connect Demonstrator",
                "version": "1.2.3"
              },
              "requesting_organization": {
                "resourceType": "Organization",
                "identifier": [
                  {
                    "system": "https://fhir.nhs.uk/Id/ods-organization-code",
                    "value": "A11111"
                  }
                ],
                "name": "Consumer organisation name"
              },
              "requesting_practitioner": {
                "resourceType": "Practitioner",
                "id": "1",
                "identifier": [
                  {
                    "system": "https://fhir.nhs.uk/Id/sds-user-id",
                    "value": "111111111111"
                  },
                  {
                    "system": "https://fhir.nhs.uk/Id/sds-role-profile-id",
                    "value": "22222222222222"
                  },
                  {
                    "system": "https://orange.testlab.nhs.uk/gpconnect-demonstrator/Id/local-user-id",
                    "value": "1"
                  }
                ],
                "name": [
                  {
                    "family": "Demonstrator",
                    "given": [
                      "GPConnect"
                    ],
                    "prefix": [
                      "Dr"
                    ]
                  }
                ]
              }
            }
      schema:
        type: string 
#-------------------------------
# Reusable responses
#-------------------------------
 responses:
    200:             # Can be referenced as '#/components/responses/200'
      description: OK
    400:             # Can be referenced as '#/components/responses/400'  
      description: Bad request
    404:             # Can be referenced as '#/components/responses/404'
      description: Not Found.  
    500:             # Can be referenced as '#/components/responses/500'  
      description: Internal Server Error
paths: {}
